# Generated by Django 4.2.7 on 2023-11-23 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.BinaryField(max_length=50)),
                ('credits', models.IntegerField(default=0)),
                ('role', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('urlImage', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('total', models.PositiveIntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('isProcessed', models.BooleanField(default=False)),
                ('productsInCart', models.ManyToManyField(to='app.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.users')),
            ],
        ),
    ]
